# Azure Pipeline for ShoppingApp

trigger:
  - master  # Change this to your main branch name

pool:
  name: Default

variables:
  buildConfiguration: 'Release'
  solution: '**/*.slnx'
  resourceGroupName: 'rg-shoppingapp' # Replace with your resource group name
  location: 'eastus' # Replace with your Azure region

jobs:
- job: Generate_Version_With_GitVersion
  displayName: 'Generate Version with GitVersion'
  dependsOn: Deploy_Azure_Container_Registry
  steps:
  - checkout: self
    fetchDepth: 0

  - task: gitversion-setup@4
    displayName: Install GitVersion
    inputs:
      versionSpec: '6.3.x'

  - task: gitversion-execute@4
    displayName: 'Run GitVersion'
    inputs:
      configFilePath: 'GitVersion.yml'
      updateAssemblyInfo: true

  - script: |
      echo "##vso[task.setvariable variable=GitVersionSemVer;isOutput=true]$(GitVersion_SemVer)"
      echo "Version: $(GitVersion_SemVer)"
    displayName: 'Set GitVersion Variables'
    name: t1

- job: DeployACR
  displayName: 'Deploy Azure Container Registry'
  dependsOn: Versioning
  steps:
  - task: AzureCLI@2
    displayName: 'Deploy ACR using Bicep'
    inputs:
      azureSubscription: 'DefaultAzureServiceConnection' # Replace with your Azure service connection name
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az group create --name $(resourceGroupName) --location $(location)
        az deployment group create \
          --resource-group $(resourceGroupName) \
          --template-file $(Build.SourcesDirectory)/deploy/acr.bicep \
          --parameters @$(Build.SourcesDirectory)/deploy/acr.parameters.json