# Azure Pipeline for ShoppingApp.

trigger:
  - master

pool:
  name: Default

variables:
  buildConfiguration: 'Release'
  solution: '**/*.sln'

jobs:
- job: Build
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET SDK'
    inputs:
      packageType: 'sdk'
      version: '9.0.x'

  - task: DotNetCoreCLI@2
    displayName: 'Restore dependencies'
    inputs:
      command: 'restore'
      projects: '$(solution)'

  - task: DotNetCoreCLI@2
    displayName: 'Build solution'
    inputs:
      command: 'build'
      projects: '$(solution)'
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - script: jb inspectcode ShoppingApp.slnx --no-build -f="Text" -o="inspection-report.txt"
    displayName: 'Run ReSharper InspectCode'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish ReSharper Report'
    inputs:
      PathtoPublish: inspection-report.txt
      ArtifactName: ReSharperReport